[target.wasm32-unknown-emscripten]
rustflags = [
    "-C", "link-arg=-s", "-C" ,"link-arg=WEBGL2_BACKWARDS_COMPATIBILITY_EMULATION=1",
    "-C", "link-arg=-s", "-C", "link-arg=USE_SDL=2",
    "-C", "link-arg=-s", "-C", "link-arg=MIN_WEBGL_VERSION=2",
    "-C", "link-arg=-s", "-C", "link-arg=MAX_WEBGL_VERSION=2",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/blank.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/fire.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/font.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/ground.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/loading2.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/loading.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_0_0.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_0_1.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_0_2.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_0_3.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_0_4.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_1_0.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_1_1.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_1_2.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_1_3.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_1_4.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_2_0.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_2_1.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_2_2.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_2_3.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_2_4.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_3_0.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_3_1.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_3_2.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_3_3.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_3_4.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_4_0.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_4_1.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_4_2.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_4_3.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/road_4_4.txt",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/yellow.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/purple.png",

"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/bus.mtl",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/bus.obj",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/bus.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/bus1.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/bus2.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/bus3.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/bus4.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/house.mtl",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/house.obj",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/house.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/house.xcf",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/office1.mtl",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/office1.obj",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/office1.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/tree.mtl",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/tree.obj",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/tree.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/man1.mtl",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/man1.obj",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/man2.mtl",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/man2.obj",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/man3.mtl",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/man3.obj",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/body.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/models/zombie.png",
"-C", "link-arg=--embed-file", "-C", "link-arg=resources/sky.png",
    "-C", "link-arg=-s", "-C", "link-arg=EXTRA_EXPORTED_RUNTIME_METHODS=[\"ccall\",\"cwrap\"]",
    "-Clink-args=--js-library main.js"
]
